name: jsam
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - netCDF4
  - xarray
  - pyyaml
  - tqdm
  - pytest
  - matplotlib
  - pip:
    - jax[cpu]
    - equinox
    - optax
